### ISSUE TITLE
var rankData ={ErrCode:-999,Data:"无访问权限"}

### ISSUE THREAD

**Issue by yhuihu** [minicloudsky/EastMoneySpider#15]
let url = "http://fund.eastmoney.com/data/rankhandler.aspx?op=dy&dt=kf&ft=all&rs=&gs=0&sc=qjzf&st=desc&sd=" + start_date
        + "&ed=" + end_date + "&es=0&qdii=&pi=1&pn=" + max_fund_num + "&dx=0&v=" + Math.random()

这个url现在随机数请求不了了

**Comment by minicloudsky** [comment]
> let url = "http://fund.eastmoney.com/data/rankhandler.aspx?op=dy&dt=kf&ft=all&rs=&gs=0&sc=qjzf&st=desc&sd=" + start_date
> + "&ed=" + end_date + "&es=0&qdii=&pi=1&pn=" + max_fund_num + "&dx=0&v=" + Math.random()
> 
> 这个url现在随机数请求不了了

刚去我服务器看了下是可以的，这个报错我之前遇到过，是由于请求时候，请求头没有加 Referer 字段，东方财富有反爬虫，会检测 Referer 来源是不是eastmoney.com或者eastmoney.com的二级域名，你可以报错信息copy过来我看下，感谢提 issue ~
![image](https://user-images.githubusercontent.com/32286819/98188371-dc115b80-1f4d-11eb-8b13-e62bcac714bc.png)
![image](https://user-images.githubusercontent.com/32286819/98188395-e6335a00-1f4d-11eb-977f-e4c635a29ff7.png)

**Comment by yhuihu** [comment]
`    public void test() throws IOException {
        Map<String, String> map = new HashMap<>();
        map.put("Referer","http://fund.eastmoney.com/");
        map.put("Host","fundapi.eastmoney.com");
        LocalDate nowDate = LocalDate.now();
        String url = "http://fund.eastmoney.com/data/rankhandler.aspx?op=dy&dt=kf&ft=all&rs=&gs=0&sc=qjzf&st=desc&sd=" + nowDate.toString() + "&ed=" + nowDate.toString() + "&es=0&qdii=&pi=1&pn=50" + "&dx=0&v=0." + Calendar.getInstance().getTimeInMillis();
        Connection connect = Jsoup.connect(url);
        connect.headers(map);
        Connection.Response execute = connect.execute();
        FundData fundData = JSONObject.parseObject(execute.body().split("var rankData = ")[1].split(";")[0], FundData.class);
    }`
经常出现java.net.SocketTimeoutException: Read timed out

**Comment by yhuihu** [comment]
```
    public void test() throws IOException {
        Map<String, String> map = new HashMap<>();
        map.put("Referer","http://fund.eastmoney.com/");
        map.put("Host","fundapi.eastmoney.com");
        LocalDate nowDate = LocalDate.now();
        String url = "http://fund.eastmoney.com/data/rankhandler.aspx?op=dy&dt=kf&ft=all&rs=&gs=0&sc=qjzf&st=desc&sd=" + nowDate.toString() + "&ed=" + nowDate.toString() + "&es=0&qdii=&pi=1&pn=50" + "&dx=0&v=0." + Calendar.getInstance().getTimeInMillis();
        Connection connect = Jsoup.connect(url);
        connect.headers(map);
        Connection.Response execute = connect.execute();
        FundData fundData = JSONObject.parseObject(execute.body().split("var rankData = ")[1].split(";")[0], FundData.class);
    }
```
经常出现java.net.SocketTimeoutException: Read timed out怎么解决

**Comment by minicloudsky** [comment]
> ```
>     public void test() throws IOException {
>         Map<String, String> map = new HashMap<>();
>         map.put("Referer","http://fund.eastmoney.com/");
>         map.put("Host","fundapi.eastmoney.com");
>         LocalDate nowDate = LocalDate.now();
>         String url = "http://fund.eastmoney.com/data/rankhandler.aspx?op=dy&dt=kf&ft=all&rs=&gs=0&sc=qjzf&st=desc&sd=" + nowDate.toString() + "&ed=" + nowDate.toString() + "&es=0&qdii=&pi=1&pn=50" + "&dx=0&v=0." + Calendar.getInstance().getTimeInMillis();
>         Connection connect = Jsoup.connect(url);
>         connect.headers(map);
>         Connection.Response execute = connect.execute();
>         FundData fundData = JSONObject.parseObject(execute.body().split("var rankData = ")[1].split(";")[0], FundData.class);
>     }
> ```
> 
> 经常出现java.net.SocketTimeoutException: Read timed out怎么解决

因为排行和自定义排行，以及获取历史净值这里数据量比较大，因此几千上万条，要么加大timeout时间，或者你分页去查询他们接口也可以解决
修改connect timout 你可以参考
https://stackoverflow.com/questions/86824/why-would-a-java-net-connectexception-connection-timed-out-exception-occur-wh
